/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Registro.java
 *
 * Created on 6/05/2009, 11:04:41 PM
 */

package gui;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.xml.parsers.ParserConfigurationException;
import javax.xml.xpath.XPathExpressionException;
import org.jvnet.substance.SubstanceLookAndFeel;
import org.jvnet.substance.watermark.SubstanceImageWatermark;
import org.xml.sax.SAXException;
import persistencia.Ingreso;

/**
 *
 * @author arquitectura
 */


public class Login extends javax.swing.JFrame {
private Ingreso ic;

    /** Creates new form Registro */
    public Login() {
        initComponents();
        
        this.setSize(800, 625);
        this.setLocationRelativeTo(null);
         ic= new Ingreso();
      
    }

    public JButton getBTN_entrar() {
        return BTN_entrar;
    }

    public void setBTN_entrar(JButton BTN_entrar) {
        this.BTN_entrar = BTN_entrar;
    }

    public JButton getBTN_registrarse() {
        return BTN_registrarse;
    }

    public void setBTN_registrarse(JButton BTN_registrarse) {
        this.BTN_registrarse = BTN_registrarse;
    }

    public JTextField getJTF_contrasena() {
        return JTF_contrasena;
    }

    public void setJTF_contrasena(JTextField JTF_contrasena) {
        this.JTF_contrasena = (JPasswordField) JTF_contrasena;
    }

    public JTextField getJTF_username() {
        return JTF_username;
    }

    public void setJTF_username(JTextField JTF_username) {
        this.JTF_username = JTF_username;
    }

    public Ingreso getIc() {
        return ic;
    }

    public void setIc(Ingreso ic) {
        this.ic = ic;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BTN_entrar = new javax.swing.JButton();
        JTF_username = new javax.swing.JTextField();
        BTN_registrarse = new javax.swing.JButton();
        JTF_contrasena = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(java.awt.Color.white);
        setMinimumSize(new java.awt.Dimension(800, 625));
        setResizable(false);
        setUndecorated(true);

        BTN_entrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/BTN_entrar.png"))); // NOI18N
        BTN_entrar.setBorder(null);
        BTN_entrar.setBorderPainted(false);
        BTN_entrar.setContentAreaFilled(false);
        BTN_entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_entrarActionPerformed(evt);
            }
        });

        JTF_username.setFont(new java.awt.Font("Tahoma", 0, 14));
        JTF_username.setForeground(new java.awt.Color(204, 204, 204));
        JTF_username.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTF_username.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        JTF_username.setOpaque(false);

        BTN_registrarse.setText("                       ");
        BTN_registrarse.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        BTN_registrarse.setBorderPainted(false);
        BTN_registrarse.setContentAreaFilled(false);

        JTF_contrasena.setForeground(new java.awt.Color(204, 204, 204));
        JTF_contrasena.setBorder(null);
        JTF_contrasena.setCaretColor(new java.awt.Color(172, 168, 153));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(383, 383, 383)
                        .addComponent(BTN_entrar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(327, 327, 327)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JTF_contrasena)
                            .addComponent(JTF_username, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                            .addComponent(BTN_registrarse, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE))))
                .addContainerGap(389, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(JTF_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(JTF_contrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(BTN_registrarse, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(154, 154, 154)
                .addComponent(BTN_entrar)
                .addContainerGap(152, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTN_entrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_entrarActionPerformed
        try {
            
            
            this.ic.entrar(this);//GEN-LAST:event_BTN_entrarActionPerformed
        } catch (ParserConfigurationException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SAXException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        } catch (XPathExpressionException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }                                          

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {

        JFrame.setDefaultLookAndFeelDecorated(true);

        SubstanceLookAndFeel.setSkin("org.jvnet.substance.skin.CremeSkin");
        //SubstanceLookAndFeel.setCurrentWatermark("org.jvnet.substance.watermark.SubstanceBinaryWatermark");//Ejemplo de aplicacion de un watermark de Substance
        SubstanceLookAndFeel.setCurrentWatermark(new SubstanceImageWatermark("http://72.29.81.246/~imindjav/images/Login.jpg"));
        SubstanceLookAndFeel.setImageWatermarkOpacity(new Float(1));

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_entrar;
    private javax.swing.JButton BTN_registrarse;
    private javax.swing.JPasswordField JTF_contrasena;
    private javax.swing.JTextField JTF_username;
    // End of variables declaration//GEN-END:variables

}
